project_id = "app-agendamento"

[functions.health]
verify_jwt = false

[functions.get-availability]
verify_jwt = false

[functions.book-appointment]
verify_jwt = false

[functions.get-cancellation]
verify_jwt = false

[functions.cancel-appointment]
verify_jwt = false

[functions.process-email-outbox]
verify_jwt = false

